export const PLAYER_ORDER = [
  "Daniel",
  "Jim",
  "Isaac",
  "Mom",
  "Isaac_2",
  "Grace",
  "Joe",
  "Nick",
  "Ella"
];

export const PICKS = {
  "Daniel": {
    "1st Round": [
      "Duke",
      "TCU",
      "St. John's",
      "Cal Baptist",
      "Louisville",
      "Michigan St.",
      "UCLA",
      "UConn",
      "Florida",
      "Clemson",
      "Vanderbilt",
      "Nebraska",
      "North Carolina",
      "Illinois",
      "Saint Mary's",
      "Houston",
      "Arizona",
      "Utah St.",
      "Wisconsin",
      "Arkansas",
      "BYU",
      "Gonzaga",
      "Miami",
      "Purdue",
      "Michigan St.",
      "Saint Louis",
      "Akron",
      "Hofstra",
      "Tennessee",
      "Virginia",
      "Kentucky",
      "Iowa St."
    ],
    "2nd Round": [
      "Duke",
      "St. John's",
      "Michigan St.",
      "Michigan St.",
      "Uconn",
      "Florida",
      "Nebraska",
      "Illinois",
      "Houston",
      "Arizona",
      "Wisconsin",
      "Gonzaga",
      "Purdue",
      "Michigan",
      "Akron",
      "Virginia"
    ],
    "Sweet 16": [
      "St. Johns",
      "Uconn",
      "Florida",
      "Houston",
      "Arizona",
      "Purdue",
      "Michigan",
      "Virginia"
    ],
    "Elite 8": [
      "Uconn",
      "Houston",
      "Arizona",
      "Michigan"
    ],
    "Final 4": [
      "Uconn",
      "Michigan"
    ],
    "Championship": [
      "Michigan"
    ]
  },
  "Jim": {
    "1st Round": [
      "Duke",
      "TCU",
      "Northern Iowa",
      "Kansas",
      "Louisville",
      "Michigan St.",
      "UCLA",
      "UConn",
      "Florida",
      "Iowa",
      "Vanderbilt",
      "Troy",
      "North Carolina",
      "Illinois",
      "Texas A&M",
      "Houston",
      "Arizona",
      "Utah St.",
      "Wisconsin",
      "Arkansas",
      "BYU",
      "Gonzaga",
      "Miami",
      "Purdue",
      "Michigan St.",
      "Saint Louis",
      "Texas Tech",
      "Alabama",
      "Tennessee",
      "Virginia",
      "Kentucky",
      "Iowa St."
    ],
    "2nd Round": [
      "Duke",
      "Iowa",
      "Michigan St.",
      "UCLA",
      "Florida",
      "Vanderbilt",
      "Illinois",
      "Texas A&M",
      "Arizona",
      "Wisconsin",
      "BYU",
      "Purdue",
      "Michigan",
      "Alabama",
      "Virginia",
      "Iowa"
    ],
    "Sweet 16": [
      "Duke",
      "Michigan St.",
      "Florida",
      "Texas A&M",
      "Arizona",
      "Purdue",
      "Michigan",
      "Iowa St."
    ],
    "Elite 8": [
      "Michigan St.",
      "Florida",
      "Arizona",
      "Iowa St."
    ],
    "Final 4": [
      "Florida",
      "Arizona"
    ],
    "Championship": [
      "Arizona"
    ]
  },
  "Isaac": {
    "1st Round": [
      "Duke",
      "Ohio St.",
      "St. John's",
      "Kansas",
      "Louisville",
      "Michigan St.",
      "UCLA",
      "UConn",
      "Florida",
      "Iowa",
      "Mcneese",
      "Nebraska",
      "North Carolina",
      "Illinois",
      "Texas A&M",
      "Houston",
      "Arizona",
      "Utah St.",
      "Wisconsin",
      "Arkansas",
      "BYU",
      "Gonzaga",
      "Miami",
      "Purdue",
      "Michigan",
      "Georgia",
      "Texas Tech",
      "Alabama",
      "Tennessee",
      "Virginia",
      "Kentucky",
      "Iowa St."
    ],
    "2nd Round": [
      "Duke",
      "Kansas",
      "Michigan St.",
      "Uconn",
      "Florida",
      "Nebraska",
      "Illinois",
      "Houston",
      "ARIZONA",
      "Arkansas",
      "Gonzaga",
      "Purdue",
      "Michigan",
      "texas",
      "virginia",
      "iowa st."
    ],
    "Sweet 16": [
      "DUKE",
      "UCONN",
      "FLORIDA",
      "HOUSTON",
      "ARIZONA",
      "PURDUE",
      "MICHIGAN",
      "IOWA ST."
    ],
    "Elite 8": [
      "UCONN",
      "FLORIDA",
      "ARIZONA",
      "MICHIGAN"
    ],
    "Final 4": [
      "FLORIDA",
      "ARIZONA"
    ],
    "Championship": [
      "ARIZONA"
    ]
  },
  "Mom": {
    "1st Round": [
      "DUKE",
      "OHIO ST.",
      "NORTHERN IOWA",
      "CAL BAPTIST",
      "SOUTH FLORIDA",
      "NORTH DAKOTA ST.",
      "UCLA",
      "UCONN",
      "FLORIDA",
      "IOWA",
      "VANDERBILT",
      "NEBRASKA",
      "VCU",
      "ILLINOIS",
      "SAINT MARY'S",
      "HOUSTON",
      "ARIZONA",
      "UTAH ST.",
      "HIGH POINT",
      "ARKANSAS",
      "BYU",
      "GONZAGA",
      "MISSOURI",
      "PURDUE",
      "MICHIGAN",
      "SAINT LOUIS",
      "AKRON",
      "ALABAMA",
      "MIAMI OF OHIO",
      "VIRGINIA",
      "SANTA CLARA",
      "TENNESSEE"
    ],
    "2nd Round": [
      "DUKE",
      "CAL BAPTIST",
      "SOUTH FLORIDA",
      "UCLA",
      "FLORIDA",
      "NEBRASKA",
      "VCU",
      "SAINT MARY'S",
      "ARIZONA",
      "HIGH POINT",
      "GONZAGA",
      "PURDUE",
      "MICHIGAN",
      "AKRON",
      "VIRGINIA",
      "SANTA CLARA"
    ],
    "Sweet 16": [
      "DUKE",
      "UCLA",
      "FLORIDA",
      "SAINT MARY'S",
      "ARIZONA",
      "GONZAGA",
      "MICHIGAN",
      "VIRGINIA"
    ],
    "Elite 8": [
      "DUKE",
      "SAINT MARY'S",
      "GONZAGA",
      "MICHIGAN"
    ],
    "Final 4": [
      "DUKE",
      "GONZAGA"
    ],
    "Championship": [
      "DUKE"
    ]
  },
  "Isaac_2": {
    "1st Round": [
      "DUKE",
      "OHIO ST.",
      "ST. JOHN'S",
      "KANSAS",
      "LOUISVILLE",
      "Michigan St.",
      "UCF",
      "UCONN",
      "FLORIDA",
      "CLEMSON",
      "MCNEESE",
      "NEBRASKA",
      "NORTH CAROLINA",
      "ILLINOIS",
      "SAINT MARY'S",
      "HOUSTON",
      "ARIZONA",
      "VILLANOVA",
      "WISCONSIN",
      "ARKANSAS",
      "BYU",
      "GONZAGA",
      "MISSOURI",
      "PURDUE",
      "MICHIGAN",
      "GEORGIA",
      "TEXAS TECH",
      "ALABAMA",
      "TENNESSEE",
      "VIRGINIA",
      "KENTUCKY",
      "IOWA ST."
    ],
    "2nd Round": [
      "DUKE",
      "KANSAS",
      "Michigan St.",
      "UCONN",
      "FLORIDA",
      "NEBRASKA",
      "ILLINOIS",
      "HOUSTON",
      "ARIZONA",
      "WISCONSIN",
      "BYU",
      "PURDUE",
      "MICHIGAN",
      "ALABAMA",
      "VIRGINIA",
      "IOWA ST."
    ],
    "Sweet 16": [
      "DUKE",
      "MICHIGAN ST.",
      "NEBRAKSA",
      "HOUSTON",
      "ARIZONA",
      "PURDUE",
      "MICHIGAN",
      "VIRGINIA"
    ],
    "Elite 8": [
      "DUKE",
      "HOUSTON",
      "PURDUE",
      "MICHIGAN"
    ],
    "Final 4": [
      "DUKE",
      "MICHIGAN"
    ],
    "Championship": [
      "MICHIGAN"
    ]
  },
  "Grace": {
    "1st Round": [
      "Duke",
      "Ohio St.",
      "St. John's",
      "Kansas",
      "Louisville",
      "Michigan St.",
      "UCLA",
      "UConn",
      "Florida",
      "Iowa",
      "Vanderbilt",
      "Nebraska",
      "North Carolina",
      "Illinois",
      "Saint Mary's",
      "Houston",
      "Arizona",
      "Villanova",
      "Wisconsin",
      "Arkansas",
      "BYU",
      "Gonzaga",
      "MIAMI",
      "Purdue",
      "Michigan",
      "Georgia",
      "Texas Tech",
      "Alabama",
      "Tennessee",
      "Virginia",
      "Kentucky",
      "Iowa St."
    ],
    "2nd Round": [
      "Duke",
      "Kansas",
      "Michigan St.",
      "UConn",
      "Florida",
      "Nebraska",
      "Illinois",
      "Houston",
      "Arizona",
      "Arkansas",
      "Gonzaga",
      "Purdue",
      "Michigan",
      "Alabama",
      "Virginia",
      "Iowa St."
    ],
    "Sweet 16": [
      "Duke",
      "UConn",
      "Florida",
      "Houston",
      "Arizona",
      "Purdue",
      "Michigan",
      "Iowa St."
    ],
    "Elite 8": [
      "Duke",
      "Florida",
      "Arizona",
      "Michigan"
    ],
    "Final 4": [
      "DUKE",
      "ARIZONA"
    ],
    "Championship": [
      "DUKE"
    ]
  },
  "Joe": {
    "1st Round": [
      "Duke",
      "TCU",
      "St. John's",
      "Kansas",
      "Louisville",
      "North Dakota St.",
      "UCLA",
      "UConn",
      "Florida",
      "Iowa",
      "Vanderbilt",
      "Nebraska",
      "North Carolina",
      "Illinois",
      "Texas A&M",
      "Houston",
      "Arizona",
      "Utah St.",
      "Wisconsin",
      "Arkansas",
      "BYU",
      "Gonzaga",
      "MIAMI",
      "Purdue",
      "Michigan",
      "Georgia",
      "Texas Tech",
      "Alabama",
      "MIAMI OF OHIO",
      "Virginia",
      "Kentucky",
      "Iowa St."
    ],
    "2nd Round": [
			"Duke",
			"St. John's",
			"Louisville",
			"Uconn",
			"Florida",
			"Vanderbilt",
			"Illinois",
			"Houston",
			"Arizona",
			"Wisconsin",
			"Gonzaga",
			"Purdue",
			"Michigan",
			"Alabama",
			"Virginia",
			"Iowa St."
    ],
    "Sweet 16": [
      "Duke",
      "UConn",
      "Florida",
      "Houston",
      "Arizona",
      "Gonzaga",
      "Michigan",
      "Iowa St."
    ],
    "Elite 8": [
      "UConn",
      "Florida",
      "Arizona",
      "Michigan"
    ],
    "Final 4": [
      "UConn",
      "Arizona"
    ],
    "Championship": [
      "ARIZONA"
    ]
  },
  "Nick": {
    "1st Round": [
      "DUKE",
      "TCU",
      "ST. JOHN'S",
      "KANSAS",
      "SOUTH FLORIDA",
      "MICHIGAN ST.",
      "UCLA",
      "UCONN",
      "FLORIDA",
      "IOWA",
      "VANDERBILT",
      "NEBRASKA",
      "NORTH CAROLINA",
      "ILLINOIS",
      "TEXAS A&M",
      "HOUSTON",
      "ARIZONA",
      "UTAH ST.",
      "WISCONSIN",
      "ARKANSAS",
      "BYU",
      "GONZAGA",
      "MISSOURI",
      "PURDUE",
      "MICHIGAN",
      "SAINT LOUIS",
      "AKRON",
      "ALABAMA",
      "TENNESSEE",
      "VIRGINIA",
      "SANTA CLARA",
      "IOWA"
    ],
    "2nd Round": [
      "DUKE",
      "KANSAS",
      "MICHIGAN ST.",
      "UCONN",
      "FLORIDA",
      "VANDERBILT",
      "ILLINOIS",
      "HOUSTON",
      "ARIZONA",
      "WISCONSIN",
      "GONZAGA",
      "PURDUE",
      "MICHIGAN",
      "ALABAMA",
      "VIRGINIA",
      "IOWA"
    ],
    "Sweet 16": [
      "DUKE",
      "MICHIGAN",
      "FLORIDA",
      "ILLINOIS",
      "ARIZONA",
      "GONZAGA",
      "MICHIGAN",
      "VIRGINIA"
    ],
    "Elite 8": [
      "DUKE",
      "ILLINOIS",
      "ARIZONA",
      "MICHIGAN"
    ],
    "Final 4": [
      "DUKE",
      "MICHIGAN"
    ],
    "Championship": [
      "MICHIGAN"
    ]
  },
  "Ella": {
    "1st Round": [
      "DUKE",
      "OHIO ST.",
      "ST. JOHN'S",
      "KANSAS",
      "LOUISVILLE",
      "MICHIGAN ST.",
      "UCLA",
      "UCONN",
      "FLORIDA",
      "IOWA",
      "VANDERBILT",
      "NEBRASKA",
      "NORTH CAROLINA",
      "ILLINOIS",
      "SAINT MARY'S",
      "HOUSTON",
      "ARIZONA",
      "VILLANOVA",
      "WISCONSIN",
      "ARKANSAS",
      "BYU",
      "GONZAGA",
      "MIAMI",
      "PURDUE",
      "MICHIGAN",
      "SAINT LOUIS",
      "TEXAS TECH",
      "ALABAMA",
      "TENNESSEE",
      "VIRGINIA",
      "KENTUCKY",
      "IOWA ST."
    ],
    "2nd Round": [
      "DUKE",
      "KANSAS",
      "MICHIGAN ST.",
      "UCONN",
      "FLORIDA",
      "NEBRASKA",
      "ILLINOIS",
      "HOUSTON",
      "ARIZONA",
      "WISCONSIN",
      "GONZAGA",
      "PURDUE",
      "MICHIGAN",
      "ALABAMA",
      "VIRGINIA",
      "IOWA ST."
    ],
    "Sweet 16": [
      "DUKE",
      "MICHIGAN ST.",
      "FLORDIA",
      "HOUSTON",
      "ARIZONA",
      "PUDUE",
      "MICHIGAN",
      "IOWA ST."
    ],
    "Elite 8": [
      "DUKE",
      "FLORIDA",
      "ARIZONA",
      "MICHIGAN"
    ],
    "Final 4": [
      "FLORIDA",
      "ARIZONA"
    ],
    "Championship": [
      "ARIZONA"
    ]
  }
};
